project_id = "tdjyfqnxvjgossuncpwm"

[functions.testar-tiny-conexao]
verify_jwt = false

[functions.alertas-estoque]
verify_jwt = false

[functions.relatorio-estoque]
verify_jwt = false

[functions.previsao-reposicao]
verify_jwt = false

[functions.sync-pedidos-rapido]
verify_jwt = false

[functions.sync-pedidos-incremental]
verify_jwt = false

[functions.sync-pedidos-tiny]
verify_jwt = false

[functions.obter-pedido-tiny]
verify_jwt = false

[functions.processar-baixa-estoque]
verify_jwt = false

# Mercado Livre integrations
[functions.mercadolivre-oauth]
verify_jwt = false  # callback precisa ser público

[functions.mercadolivre-webhook]
verify_jwt = false  # notificações do ML

[functions.mercadolivre-orders-proxy]
verify_jwt = true   # chamada autenticada pelo app

[functions.mercadolivre-refresh-token]
verify_jwt = true   # exige JWT para atualizar tokens

[functions.tiny-orders]
verify_jwt = true